const { Client } = require('pg');

const client = new Client({
  connectionString: 'postgres://postgres.tsmylypcdkckcxyvsvkq:Tung1990Aa%40@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres'
});

async function run() {
  await client.connect();
  
  try {
    const res = await client.query(`
      SELECT column_default, identity_generation
      FROM information_schema.columns 
      WHERE table_name = 'app_settings' AND column_name = 'id';
    `);
    console.log(res.rows);

    await client.query(`ALTER TABLE public.app_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;`);
    console.log("SUCCESS!");

  } catch(e) {
    console.log("Err:", e);
  }

  await client.end();
}

run();
